name: Build/Release

on:
 push:
   tags:
     - '*'
 workflow_dispatch:
   branches:
     - main
  
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          path: .
    
      # Build
      - name: Build and Zip
        run: |
            make docker-compile-zip
      - uses: actions/upload-artifact@v3
        with:
            name: linux
            path: "**/*.zip"
    
      # Release    
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux

      - name: Zip Files
        run: |
          ls -lha
          find . -name "*.zip"
          zip linux.zip `find . -name "*.zip" -print`

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # Identify if this is a pre release by checking if the tag name contains -rc, -b, -a
          # prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          files: linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}